### ISSUE TITLE
Android Auto Support

### ISSUE THREAD

**Issue by ghost** [PaulWoitaschek/MaterialAudiobookPlayer#231]
There are NO audiobook players for Android Auto and it could be a wonderful niche to get in to early. I have no idea if the Auto program is open yet or still only if you're partnered with Google, but I think the first audiobook player out for it would get some huge notoriety.

**Comment by Ph1b** [comment]
When I have more time I'll work on it. In the meantime if anyone wants to start on this, give me a quick notice ;-)

**Comment by PaulWoitaschek** [comment]
So finally some basic support here. Can you try it and give feedback?

[player.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/170920/player.zip)

**Comment by Streets-ahead-of-you** [comment]
I uninstalled the main app and installed that zip but it's not showing up in android auto music section.

**Comment by PaulWoitaschek** [comment]
Its already integrated in the latest version.

**Comment by Streets-ahead-of-you** [comment]
I uninstalled all versions of the app then installed the the app off the play store (v2.7) 
Its plugged into a Skoda Octavia, other apps come up like Pocketcast and Spotify. Should it just come up under the headphone icon?

**Comment by Streets-ahead-of-you** [comment]
After the last app update everything seems to be working.

**Comment by Streets-ahead-of-you** [comment]
With the latest update (V 2.7.2.1) the player has gone missing again from the AA interface. Have tried an uninstall and reinstall but still nothing. Any suggestions?

**Comment by PaulWoitaschek** [comment]
Which version were you using before? Fdroid?

**Comment by Streets-ahead-of-you** [comment]
What ever the latest version off the play store was, before the last update.

**Comment by PaulWoitaschek** [comment]
Are you a participant of the beta?

**Comment by Streets-ahead-of-you** [comment]
No, but i would be happy to test it out

**Comment by allmynamesweretakenomoreideas** [comment]
With v2.7.2.1 MP does not show up on android auto screen. (AA v1.6.240030). And play store does not list MP under AA compatible apps. What are the requirements for an app to get AA certified?

**Comment by TangoIndia** [comment]
Hi, I have joined the beta, and am using the current 2.7.2.2 version of the App and i can also confirm that it doesn't work with Android Auto, but would love it to!
However your app is fantastic. Thanks!

**Comment by TangoIndia** [comment]
Hi, does anyone have a solution for this? thanks

**Comment by aperomsik** [comment]
Now that Android Auto can work without specific support from the car, it would be great to get this sorted.

**Comment by PaulWoitaschek** [comment]
I'm really willig to bring Android Auto Support to this app, but it just doesn't work.
I implemented everything but the app does not show up at all in the list of apps.

So yeah, any support is appreciated.

**Comment by ztNFny** [comment]
I'm not really familar with Kotlin but I'm assuming PlaybackService.kt is extending MediaBrowserService properly? Otherwise I really can't spot any errors, Manifest and stuff seems to be in order - or maybe the tools:ignore="ExportedService"?
Are you aware of this sample project? https://github.com/googlesamples/android-MediaBrowserService

**Comment by PaulWoitaschek** [comment]
`tools:ignore` just supresses  a lint warning, that's nothing that end up in the production version.
I just compiled that sample project today and it also doesn't show up in android auto.

Todays update got refused
> - Your app does not support all of the required voice commands. The app does not appear
on the media picker. Voice commands are not acknowledged when used on AA.

> You can read more about how to support Voice Actions here: https://developer.android.com/training/auto/audio/index.html#support_voice 

Where the important line is
> The app does not appear on the media picker.

**Comment by aperomsik** [comment]
Perhaps they are saying that the app will not be allowed on the media picker if it does not support the required voice commands?

**Comment by ztNFny** [comment]
Wanted to look into this but am still having some trouble with Kotlin. Could you post apk with the Auto entries and I'll try to figure something out with the binary.
Also maybe have a look at https://bitbucket.org/ChernyshovYuriy/openradio/src, an Auto-enabled OSS app.

**Comment by aperomsik** [comment]
There is also a list of requirements [here](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MusicService.java) in a long comment in the demo player. I might be missing something due to Kotlin but to me it smells like you might be missing the line " setSessionToken(mSession.getSessionToken()); "

**Comment by PaulWoitaschek** [comment]
> Perhaps they are saying that the app will not be allowed on the media picker if it does not support the required voice commands?

Also with voice intent it doesn't even show up. 

> Wanted to look into this but am still having some trouble with Kotlin. Could you post apk with the Auto entries and I'll try to figure something out with the binary.

I'm not next to a machine the next days. Just enable the auto entry in the manifest I built.

> There is also a list of requirements here in a long comment in the demo player.

 Which ones are we missing? The demo player does not show up neither. 

> it smells like you might be missing the line " setSessionToken(mSession.getSessionToken())

That happens [here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/playback/PlaybackService.kt#L138)

**Comment by aperomsik** [comment]
Finally got a chance to play a little more. I just took the master branch and reverted the commit to disable auto registration. The app does not appear for me on the phone screen in android auto, but it does appear in the "desktop head unit" emulator for developers. First you have to put the Android Auto app in developer mode, by going to the About screen and tapping the header ten times. After that Material Player still doesn't appear in Android Auto's player list on the phone but it does appear in the DHU. (Not sure if you have to switch "app mode" to "developer" in the developer settings menu... it seems to appear without that for me but I did have it set to developer earlier.)

So I'm guessing you have to test it in that mode, then when you believe it's working, including the voice actions, then you submit it to Play again and their reviewers decide whether to enable it for everybody if it meets their quality criteria.

Two asides:

(1) When testing earlier this week the master branch wasn't letting me add folders from my SD card. That's working better now due to your recent work.

(2) When testing with the DHU sometimes the forward/back skip buttons would cause the audio to pause. Skipping again resumes playback. I have seen this behavior in my car too, over regular bluetooth audio connection. In the car it seems most likely to happen if I push the "skip back" button twice.

![screenshot from 2016-11-12 18-56-35](https://cloud.githubusercontent.com/assets/500320/20242823/97dcdfe2-a90a-11e6-92c7-6300850a37b7.png)

**Comment by PaulWoitaschek** [comment]
Hm; I gave it another try. According to [this](https://stackoverflow.com/questions/31953155/android-auto-voice-cannot-perform-play-x-on-y) only the intent is required and the service should handle it.

However the whole android auto thing is very frustrating. The ADH most of the time does not start, stays black or does not work in other ways.
I cannot test the voice commands at all. When I use `mic play voice/pause.wav` like descripbed [here](https://developer.android.com/training/auto/testing/index.html) it just responds with

> Not sure how to help with... "Pause music"

Thats stupid - even the google play app responds with that message.

**Comment by PaulWoitaschek** [comment]
Please test it:

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.9.1.4

**Comment by PaulWoitaschek** [comment]
Rejected.

> Your app does not support all of the required voice commands. When initiating "Play X on Y", App acknowledges the command but does not pause or change audio.
You can read more about how to support Voice Actions here: https://developer.android.com/training/auto/audio/index.html#support_voice

I don't understand what they expect. Why should it pause when someone says Plax X on Y?

**Comment by aperomsik** [comment]
Sounds like Y is the app name -- and perhaps they are saying if the user says to play X on some other app, your app should pause. For your app, X could be used to switch to a different book I suppose. 

A few days after my last comment, a post in the linked Plus group detailed how to enable testing of not-yet-approved apps in on-phone mode. The part I had been missing was the "Unknown Sources" check mark in the Android Auto developer settings menu. I had to reboot after changing that setting to make it take effect. (I had built an apk based on whatever was your current master at the time, with the manifest setting for auto support restored.) They still recommend testing both ways.

**Comment by aperomsik** [comment]
I'm having trouble deciding whether the behavior is your app's fault or not.  I'm trying voice commands like:

"Play in Material Audiobook Player"
"Play in MDPlayer"
"Play in Listen Audiobook Player"

The intention seems to be to allow me to switch between players with voice commands... but it doesn't work very well. Regardless of which app is active and which I am asking for, it almost always just presses play in the active app.

**Comment by PaulWoitaschek** [comment]
I think you have to say `Play WhatEver in PlayerName`.

I asked for detailed feedback:

>Hi Paul,
>
>Thanks for reaching out to the Android Auto team.
>
>During review, we weren't able to get voice commands to work properly. This was in part due to the audio not pausing when initiating voice commands. Example:
>
>- Audio is playing in Auto
>- User taps microphone to initiate voice commands
>- Audio continues to play over voice command prompts
>- App cannot recognize user request due to audio playing in background
>
>Additionally, while testing voice commands with the audio paused, the app would acknowledge our request of "Play X" but the audio remained paused and didn't play another track. This is why we've rejected your app for Voice Commands at this time.
>
>Please work to address the above behavior in a new APK and upload it into the Developer Console for our review. We're happy to take another look

I cannot confirm that behavior with the emulator. It pauses the player when I press on record.
About the other issue: I just implemented basic search with 9e1b0da6349eb74f6032c9e11f8022f4abe48b77

But I cannot test anything as the ADH always response with "No idea what you mean by Pause Music". All the samples don't work - neither with MAP nor with google music.
I commented in the G+ group [here](https://plus.google.com/+PaulWoitaschek/posts/GCMq8Dk5Svf)

But as a developer the whole android audio thing is really frustrating as it's just not working

**Comment by eturk1** [comment]
I'm just using the app on a Nexus 6P & Android 7.1.1 (no head unit)
https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead

thanks a bunch for attacking this feature, even though sounds frustrating at times!

happy to test betas in this scenario.

**Comment by PaulWoitaschek** [comment]
Okay, update got approved :)

I implemented search from voice.
Also I added a check if android auto is connected and pause playback instead of lowering volume when a voice message comes in.

Looking forward for your feedback!

**Comment by PaulWoitaschek** [comment]
False alarm!

>I understand your app was recently not approved for Android Auto. I looked into the notes as to why it wasn't approved and found that when using the voice command the volume doesn't turn off or at least go low enough to hear the voice command. the other issue is that when the voice command does work it doesn't play the audio for it. Once these are adjusted, please resubmit your app fro Android Auto and we will gladly review your app for Android Auto again.

**Comment by PaulWoitaschek** [comment]
Fell free to join development everybody!

**Comment by ynvtlmr** [comment]
Not sure if this is still in active development, but figured I'd note it is still an issue on my device:
MaterialAudiobookPlayer does not appear in Google Auto as an audio playback app
on Google Pixel, Android 7.1.2

**Comment by PaulWoitaschek** [comment]
It's because it's not approved, see the comments above. Currently this is on hold till I find time for this or someone else does.

**Comment by Eifelschaf** [comment]
Hi Paul,
since I have a real head unit now I'd like to jump into this. Do you have any more info on how to test the app myself? Do I have to sign the app in a specific way to allow it to work with android auto or will any development version just show up?

**Comment by PaulWoitaschek** [comment]
There is a section on the manifest that is commented out. Uncomment that and start the app. I'm not sure about further steps.

**Comment by Eifelschaf** [comment]
I'll let you know if I run into anything. Is the audio not nuting part the only issue that remains (as there's quite a long list of things to be done for auto apparently)

**Comment by PaulWoitaschek** [comment]
Yes, what's listed under false alarm is what's remaining. 
Also I'm not sure about the search functionality. Is currently very rudimentary.

**Comment by Eifelschaf** [comment]
My findings so far: the pause seems to work well (I'll test this in the coming days with my car/real head unit, perhaps that's different from the simulator). However the search is not working at all.

I can't even see the callback being called. Is it possible, that the MediaSession is not active at the right time?

**Comment by Eifelschaf** [comment]
Hi @PaulWoitaschek 

I'll need a bit of help here. I'm not familiar with Kotlin (yet), but perhaps you can give me a hint. I continuously get the message that kolin line breakpoints are not supported by my debugger. do I have to have some specific setting to allow me to debug the app?

**Comment by PaulWoitaschek** [comment]
Are you using Android studio and installed the kotlin plugin? Debugging should work as usual. Just not inside inline functions as they are - as the name says: unlined by the compiler.

If you have further issues we can Skype if you like.

**Comment by Eifelschaf** [comment]
I managed to get some queries through to the app (although the google recognition in german as well as english is less than reliable). To me it looks like it's working well. Audio is paused for the query, and if it's recognized as a valid "play" query the command is forwarded to the app properly and it look for a book. The search could be a bit more sophisticated (I might go to this one as teh next step), but the general aproach seems to be fine. I sent you a skype request for more discussions, perhaps we can get this through the google play testing soon together.

**Comment by Eifelschaf** [comment]
Hi Paul,

I implemented the voice search queries for Android auto (or any other voice query, for example from google now) here https://github.com/Eifelschaf/MaterialAudiobookPlayer/commit/a3dbd67cb92611ddab5ba61256703217991612b5
I just have one minor issue. Is it possible to start playing at a specific title? There are some commands that include a title in the query and I'd like to start the playback at the given chapter if I find a match. Right now the app will just play the book that contains the chapter.

**Comment by PaulWoitaschek** [comment]
That would be possible but I think it's better not to do it. Else when voice detection is flaky you might lose the latest position in your audiobook. So I'd rather do the book switching functionality only.

**Comment by nioncode** [comment]
It's probably a really uncommon situation to play exactly `Chapter 23` from `Book 42`.
Usually, you just want to either resume the last played book or switch to another book.

Does skipping back and forth between chapters work via voice?

**Comment by Eifelschaf** [comment]
Titles are just supported by the voice search API, but I'll remove the title specific code. Skipping chapters should work via the next/previous commands.

**Comment by PaulWoitaschek** [comment]
Thanks :)

To summarize our skype talk:

I would test the `BookFinder` isolated without the activity. Therefore I would inject the required dependencies through the constructor and mock them using mockito.

Also `PlayerController` should be favored over `MediaPlayer` as  it starts the service if necessary. `MediaPlayer` should ideally be controlled by the service.

**Comment by Eifelschaf** [comment]
Just one more question: The current way of testing with the activity also tests the received intents (as they are standardized) so I guess it might make sense to keep it in some way or another to test the complete workflow. The guys at google might do nothing else. Any idea on how to keep these tests in an ideal way and still isolate the `BookFinder`?

**Comment by PaulWoitaschek** [comment]
That would be a different test I guess.

We could setup something like https://github.com/fabioCollini/DaggerMock.

So we could inject a mocked version of `BookFinder`.

Then we only need to do a `verify(bookFinder).query(any(),any())`.

**Comment by Eifelschaf** [comment]
For the daggermock we'd have to refactor all @Inject annotations to be inside a module. I guess that's something that you should do. I will see if I can isolate the `BookFinder`

**Comment by PaulWoitaschek** [comment]
Can you make a pull request? Then I'll prepare everything for the test

**Comment by Eifelschaf** [comment]
Done.

**Comment by PaulWoitaschek** [comment]
There are merge conflicts.

**Comment by Eifelschaf** [comment]
I merged all your commits. Can I resolve them? (it says write access is required)

**Comment by Eifelschaf** [comment]
The issues are fixed, but circleCI fails at exoplayer. I guess that's also the reason why it says "circleci failing" on the fromt page?

**Comment by PaulWoitaschek** [comment]
Yes, and I have no idea how to fix that :)

**Comment by Eifelschaf** [comment]
if you don't mind I'll add a new issue/thread for that :) I think I found something, but don't want to spam here.

**Comment by PaulWoitaschek** [comment]
Wow it got approved!

However it still needs approvements as it works very poorly for me.

**Comment by Eifelschaf** [comment]
Give me more details about what fails and I'll get on to it 😀

Paul Woitaschek <notifications@github.com> schrieb am Mi., 24. Mai 2017,
07:27:

**Comment by Eifelschaf** [comment]
After having used the android auto integration for a week now I have a few improvements no my mind and would like to have your opinion on them:

1. It would be nice if we would have a previous/next chapter button in addition to the skip back/forward buttons on the main UI. At least in some sort of overflow menu. It's hard to jump to the beginning of a lengthy chapter in the current implementation
2. It would also be great to just display the current book on the main screen when the app is opened instead of "only" having it on top of the list.

On Android Wear I think I could fix the image loading of the cover artworks at the same time, but that's another topic.

What do you guys think about that? I'd be happy do do the work, but let me know if there's anything against any of the points above (or something you noticed as missing)

**Comment by PaulWoitaschek** [comment]
Yeas sure, I don't think anything speaks against that. 

> It would also be great to just display the current book on the main screen when the app is opened instead of "only" having it on top of the list.

This should be achievable by setting the current book in paused state once connected to android auto.

> It would be nice if we would have a previous/next chapter button in addition to the skip back/forward buttons on the main UI. At least in some sort of overflow menu. It's hard to jump to the beginning of a lengthy chapter in the current implementation

I assume this is a limitation of Android Auto. You really cannot control the UI. If you find anything, feel free to implement it. However I find the importance of the seek functionality way greater than the importance of the chapter skip functionality.

**Comment by Eifelschaf** [comment]
I've seen this kind of secondary buttons on some podcast players.

**Comment by PaulWoitaschek** [comment]
Thanks! For further improvements please open a new ticket.
